# Generated by Django 3.2.5 on 2024-03-16 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_class', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Eleves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=200)),
                ('lieu_naiss', models.CharField(max_length=100)),
                ('date_naiss', models.DateTimeField()),
                ('email', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('sexe', models.CharField(max_length=30)),
                ('classes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scolaire.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Matieres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_matiere', models.CharField(max_length=100)),
                ('classes', models.ManyToManyField(to='scolaire.Classes')),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_niveau', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Professeurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=100)),
                ('date_naiss', models.DateTimeField()),
                ('lien_naiss', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=200)),
                ('diplome', models.CharField(max_length=200)),
                ('classes', models.ManyToManyField(related_name='professeurs_classes', to='scolaire.Classes')),
                ('eleves', models.ManyToManyField(related_name='professeurs_eleves', to='scolaire.Eleves')),
                ('matieres', models.ManyToManyField(to='scolaire.Matieres')),
                ('niveau', models.ManyToManyField(related_name='professeurs_niveau', to='scolaire.Niveau')),
            ],
        ),
        migrations.AddField(
            model_name='niveau',
            name='professeur',
            field=models.ManyToManyField(related_name='niveau_professeurs', to='scolaire.Professeurs'),
        ),
        migrations.AddField(
            model_name='eleves',
            name='matiere',
            field=models.ManyToManyField(to='scolaire.Matieres'),
        ),
        migrations.AddField(
            model_name='eleves',
            name='professeurs',
            field=models.ManyToManyField(related_name='eleves_professeurs', to='scolaire.Professeurs'),
        ),
        migrations.AddField(
            model_name='classes',
            name='niveau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scolaire.niveau'),
        ),
        migrations.AddField(
            model_name='classes',
            name='professeurs',
            field=models.ManyToManyField(related_name='classes_professeurs', to='scolaire.Professeurs'),
        ),
    ]
